# Generated by Django 2.0.8 on 2020-07-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('eventTime', models.DateField()),
                ('eventType', models.CharField(max_length=50)),
                ('eventNote', models.CharField(max_length=150)),
            ],
        ),
    ]
